import {
  Button,
  Col,
  Form,
  Input,
  Layout,
  Radio,
  RadioChangeEvent,
  Row,
  Select,
  Upload,
  Image
} from "antd";
import WorkInquiryWrapper from "./styles";
const { Content, Footer, Sider } = Layout;
import useTranslation from "@/hooks/useTranslation";
import Head from "next/head";
import Header from "@/components/Header";
import React, { useState } from "react";
import TypeOfSale from "./component/TypeOfSale";
import PriceSet from "./component/PriceSet";
import Duration from "./component/Duration";
import MoreOptions from "./component/MoreOption";
import Summary from "./component/Summary";

const WorkInquiry = () => {
  const translation = useTranslation();
  const [checkType, setCheckType] = useState<number>(1);
  const [checkType2, setCheckType2] = useState<number>(1);

  return (
    <>
      <Head>
        <title>NFT Art Marketplace ZEZI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={{ minHeight: "100vh", background: "#fff" }}>
        <Header />
        <Content className="relative">
          <WorkInquiryWrapper>
            <h1 className="absolute top-[40px] left-[70px] text-black	text-2xl font-bold ">
              List for sale
            </h1>
            <div className="flex flex-row items-center mb-[24px]">
              <Image
                className="w-[310px] h-[202px]"
                src={"images/card.png"}
                alt="card"
              />
              <div className="flex flex-col justify-center ml-[24px]">
                <label className="text-black text-[20px] font-bold mb-[8px]">
                  The Metapuffers 2.0
                </label>
                <span className="text-black	text-[16px] mb-[16px]">
                  Untitled Collection #1
                </span>
                <span className="text-black text-[24px] font-bold">
                  0.005 ETH
                </span>
              </div>
            </div>

            <TypeOfSale checkType={checkType} setCheckType={setCheckType} />

            <TypeOfSale checkType={checkType2} setCheckType={setCheckType2} />

            <PriceSet />

            <Duration />

            <MoreOptions />

            <Summary />
            <Button
              type="primary"
              htmlType="submit"
              className="w-[90px] mt-[20px]"
            >
              Complete
            </Button>
          </WorkInquiryWrapper>
        </Content>
      </Layout>
    </>
  );
};

export default WorkInquiry;
