import Head from 'next/head'
import { Noto_Sans_JP } from 'next/font/google'
import { Inter } from 'next/font/google'
import { Layout, Tabs, Card, Button, Image } from 'antd'
import Link from 'next/link'

const { Content, Footer, Sider } = Layout;
import Header from "@/components/Header"
import Intro from "./homepage/components/Intro"
import GridCard from "./homepage/components/GridCard"
import ListGridCard from "./homepage/components/ListGridCard"
import Table from "./homepage/components/Table"
const notoSansJp = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  variable: '--noto-sans_JP',
  preload: true,
})
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export default function Home() {
  return (
    <>
      <Head>
        <title>NFT Art Marketplace ZEZI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={{ minHeight: '100vh', background: '#fff' }} className={`${inter.variable} font-sans`}>
        <Header />
        <Content className='container'>
          <Intro />
          <GridCard />
          {/* <ListGridCard /> */}
          <Table />
          
          <Button type="primary">Primary Button</Button>
          <Button>Primary Button</Button>
          <Link href="/test-page">GO to test page</Link>
        </Content>
      </Layout>
    </>
  )
}